#!/usr/bin/env bash

set -eu

translators="$1"

echo "Translating SplashKit Core to ${translators}"

./src/main.rb \
  --verbose \
  --no-color \
  -i /splashkit/ \
  -o /splashkit/generated \
  -g "$translators" \
  
